version: '3'
services:
  # Airflow initialization: sets up the metadata DB and creates the admin user.
  airflow-init:
    image: apache/airflow:2.5.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:masterclass@host.docker.internal:5432/rdt_data
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-postgres psycopg2"
    volumes:
      - ./dags:/opt/airflow/dags
    entrypoint: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin"

  webserver:
    image: apache/airflow:2.5.0
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:masterclass@host.docker.internal:5432/rdt_data
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-postgres psycopg2"
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    # Uncomment extra_hosts for Linux if host.docker.internal is not automatically resolved:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: webserver

  scheduler:
    image: apache/airflow:2.5.0
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:masterclass@host.docker.internal:5432/rdt_data
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey"
      _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-postgres psycopg2"
    volumes:
      - ./dags:/opt/airflow/dags
    # Uncomment extra_hosts for Linux if needed:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: scheduler
